[2024-06-06T16:27:00.242+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-06T16:27:00.287+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_testConnection_v1.test_boto manual__2024-06-06T16:26:57.433526+00:00 [queued]>
[2024-06-06T16:27:00.325+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_testConnection_v1.test_boto manual__2024-06-06T16:26:57.433526+00:00 [queued]>
[2024-06-06T16:27:00.326+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-06T16:27:00.356+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): test_boto> on 2024-06-06 16:26:57.433526+00:00
[2024-06-06T16:27:00.373+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dag_testConnection_v1', 'test_boto', 'manual__2024-06-06T16:26:57.433526+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/TestConnectionDag.py', '--cfg-path', '/tmp/tmps1rd77dg']
[2024-06-06T16:27:00.378+0000] {standard_task_runner.py:91} INFO - Job 3: Subtask test_boto
[2024-06-06T16:27:00.389+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=473) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-06-06T16:27:00.392+0000] {standard_task_runner.py:63} INFO - Started process 479 to run task
[2024-06-06T16:27:00.509+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_testConnection_v1.test_boto manual__2024-06-06T16:26:57.433526+00:00 [running]> on host 6c00989aad97
[2024-06-06T16:27:00.752+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_testConnection_v1' AIRFLOW_CTX_TASK_ID='test_boto' AIRFLOW_CTX_EXECUTION_DATE='2024-06-06T16:26:57.433526+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-06T16:26:57.433526+00:00'
[2024-06-06T16:27:00.756+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-06T16:27:00.818+0000] {logging_mixin.py:188} INFO - <***.providers.amazon.aws.hooks.s3.S3Hook object at 0x7f5882644f80>
[2024-06-06T16:27:00.833+0000] {base.py:84} INFO - Using connection ID 's3_conn' for task execution.
[2024-06-06T16:27:00.834+0000] {connection_wrapper.py:387} INFO - AWS Connection (conn_id='s3_conn', conn_type='aws') credentials retrieved from extra.
[2024-06-06T16:27:01.509+0000] {s3.py:298} INFO - Bucket "bucket0" does not exist
[2024-06-06T16:27:01.510+0000] {logging_mixin.py:188} INFO - False
[2024-06-06T16:27:01.529+0000] {logging_mixin.py:188} INFO - bucket:False, file exist:False
[2024-06-06T16:27:01.531+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-06-06T16:27:01.533+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-06T16:27:01.553+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=dag_testConnection_v1, task_id=test_boto, run_id=manual__2024-06-06T16:26:57.433526+00:00, execution_date=20240606T162657, start_date=20240606T162700, end_date=20240606T162701
[2024-06-06T16:27:01.599+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-06T16:27:01.637+0000] {taskinstance.py:3498} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-06-06T16:27:01.643+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
