[2024-06-08T08:39:08.885+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-08T08:39:08.940+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_t1.upload_day manual__2024-06-08T07:11:19.232646+00:00 [queued]>
[2024-06-08T08:39:08.970+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_t1.upload_day manual__2024-06-08T07:11:19.232646+00:00 [queued]>
[2024-06-08T08:39:08.971+0000] {taskinstance.py:2306} INFO - Starting attempt 5 of 5
[2024-06-08T08:39:09.004+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): upload_day> on 2024-06-08 07:11:19.232646+00:00
[2024-06-08T08:39:09.017+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=3693) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-06-08T08:39:09.021+0000] {standard_task_runner.py:63} INFO - Started process 3701 to run task
[2024-06-08T08:39:09.037+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'etl_t1', 'upload_day', 'manual__2024-06-08T07:11:19.232646+00:00', '--job-id', '68', '--raw', '--subdir', 'DAGS_FOLDER/Etl_Dag.py', '--cfg-path', '/tmp/tmprfdo_pgz']
[2024-06-08T08:39:09.042+0000] {standard_task_runner.py:91} INFO - Job 68: Subtask upload_day
[2024-06-08T08:39:09.171+0000] {task_command.py:426} INFO - Running <TaskInstance: etl_t1.upload_day manual__2024-06-08T07:11:19.232646+00:00 [running]> on host 6c00989aad97
[2024-06-08T08:39:09.350+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_t1' AIRFLOW_CTX_TASK_ID='upload_day' AIRFLOW_CTX_EXECUTION_DATE='2024-06-08T07:11:19.232646+00:00' AIRFLOW_CTX_TRY_NUMBER='5' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-08T07:11:19.232646+00:00'
[2024-06-08T08:39:09.354+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-08T08:39:09.396+0000] {logging_mixin.py:188} INFO - from args: None
[2024-06-08T08:39:09.441+0000] {base.py:84} INFO - Using connection ID 's3_conn' for task execution.
[2024-06-08T08:39:09.451+0000] {connection_wrapper.py:387} INFO - AWS Connection (conn_id='s3_conn', conn_type='aws') credentials retrieved from extra.
[2024-06-08T08:39:10.378+0000] {logging_mixin.py:188} INFO - landing prefix for 20240608 already exist
[2024-06-08T08:39:10.387+0000] {logging_mixin.py:188} INFO - transform prefix for 20240608 already exist
[2024-06-08T08:39:10.389+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-06-08T08:39:10.391+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-08T08:39:10.408+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=etl_t1, task_id=upload_day, run_id=manual__2024-06-08T07:11:19.232646+00:00, execution_date=20240608T071119, start_date=20240608T083908, end_date=20240608T083910
[2024-06-08T08:39:10.459+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-08T08:39:10.495+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-08T08:39:10.501+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
