[2024-06-06T16:27:00.340+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-06T16:27:00.394+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_testConnection_v1.test_mysql_connection manual__2024-06-06T16:26:57.433526+00:00 [queued]>
[2024-06-06T16:27:00.417+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_testConnection_v1.test_mysql_connection manual__2024-06-06T16:26:57.433526+00:00 [queued]>
[2024-06-06T16:27:00.419+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-06T16:27:00.448+0000] {taskinstance.py:2330} INFO - Executing <Task(MySqlOperator): test_mysql_connection> on 2024-06-06 16:26:57.433526+00:00
[2024-06-06T16:27:00.470+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dag_testConnection_v1', 'test_mysql_connection', 'manual__2024-06-06T16:26:57.433526+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/TestConnectionDag.py', '--cfg-path', '/tmp/tmp8v32skkb']
[2024-06-06T16:27:00.477+0000] {standard_task_runner.py:91} INFO - Job 4: Subtask test_mysql_connection
[2024-06-06T16:27:00.484+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=474) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-06-06T16:27:00.488+0000] {standard_task_runner.py:63} INFO - Started process 480 to run task
[2024-06-06T16:27:00.609+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_testConnection_v1.test_mysql_connection manual__2024-06-06T16:26:57.433526+00:00 [running]> on host 6c00989aad97
[2024-06-06T16:27:00.792+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_testConnection_v1' AIRFLOW_CTX_TASK_ID='test_mysql_connection' AIRFLOW_CTX_EXECUTION_DATE='2024-06-06T16:26:57.433526+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-06T16:26:57.433526+00:00'
[2024-06-06T16:27:00.796+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-06T16:27:00.824+0000] {sql.py:276} INFO - Executing: select * from dest.pokedex
[2024-06-06T16:27:00.845+0000] {base.py:84} INFO - Using connection ID 'mysql_conn' for task execution.
[2024-06-06T16:27:00.862+0000] {base.py:84} INFO - Using connection ID 'mysql_conn' for task execution.
[2024-06-06T16:27:00.921+0000] {sql.py:470} INFO - Running statement: select * from dest.pokedex, parameters: None
[2024-06-06T16:27:00.925+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-06T16:27:00.926+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 282, in execute
    output = hook.run(
             ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 418, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 475, in _run_command
    cur.execute(sql_statement)
  File "/home/airflow/.local/lib/python3.12/site-packages/MySQLdb/cursors.py", line 179, in execute
    res = self._query(mogrified_query)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/MySQLdb/cursors.py", line 330, in _query
    db.query(q)
  File "/home/airflow/.local/lib/python3.12/site-packages/MySQLdb/connections.py", line 261, in query
    _mysql.connection.query(self, query)
MySQLdb.ProgrammingError: (1146, "Table 'dest.pokedex' doesn't exist")
[2024-06-06T16:27:00.941+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=dag_testConnection_v1, task_id=test_mysql_connection, run_id=manual__2024-06-06T16:26:57.433526+00:00, execution_date=20240606T162657, start_date=20240606T162700, end_date=20240606T162700
[2024-06-06T16:27:00.966+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 4 for task test_mysql_connection ((1146, "Table 'dest.pokedex' doesn't exist"); 480)
[2024-06-06T16:27:00.995+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-06T16:27:01.022+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-06T16:27:01.025+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
