[2024-06-09T10:50:54.186+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-09T10:50:54.231+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_t1.upsertDbTest manual__2024-06-09T10:50:44.895269+00:00 [queued]>
[2024-06-09T10:50:54.255+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_t1.upsertDbTest manual__2024-06-09T10:50:44.895269+00:00 [queued]>
[2024-06-09T10:50:54.258+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-09T10:50:54.288+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): upsertDbTest> on 2024-06-09 10:50:44.895269+00:00
[2024-06-09T10:50:54.321+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=924) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-06-09T10:50:54.323+0000] {standard_task_runner.py:63} INFO - Started process 932 to run task
[2024-06-09T10:50:54.321+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'etl_t1', 'upsertDbTest', 'manual__2024-06-09T10:50:44.895269+00:00', '--job-id', '90', '--raw', '--subdir', 'DAGS_FOLDER/Etl_Dag.py', '--cfg-path', '/tmp/tmp00yz1h1b']
[2024-06-09T10:50:54.326+0000] {standard_task_runner.py:91} INFO - Job 90: Subtask upsertDbTest
[2024-06-09T10:50:54.448+0000] {task_command.py:426} INFO - Running <TaskInstance: etl_t1.upsertDbTest manual__2024-06-09T10:50:44.895269+00:00 [running]> on host 6c00989aad97
[2024-06-09T10:50:54.690+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_t1' AIRFLOW_CTX_TASK_ID='upsertDbTest' AIRFLOW_CTX_EXECUTION_DATE='2024-06-09T10:50:44.895269+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-09T10:50:44.895269+00:00'
[2024-06-09T10:50:54.692+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-09T10:50:54.744+0000] {logging_mixin.py:188} INFO - from args: None
[2024-06-09T10:50:54.790+0000] {base.py:84} INFO - Using connection ID 's3_conn' for task execution.
[2024-06-09T10:50:54.792+0000] {connection_wrapper.py:387} INFO - AWS Connection (conn_id='s3_conn', conn_type='aws') credentials retrieved from extra.
[2024-06-09T10:50:56.128+0000] {logging_mixin.py:188} INFO - bucket or prefix not found
[2024-06-09T10:50:56.149+0000] {logging_mixin.py:188} INFO - exiting...
[2024-06-09T10:50:56.157+0000] {logging_mixin.py:188} INFO - 20240609/output/20240609_finalRes.csv
[2024-06-09T10:50:56.197+0000] {logging_mixin.py:188} INFO - file/key in bucket dont exist
[2024-06-09T10:50:56.199+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-06-09T10:50:56.200+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-09T10:50:56.223+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=etl_t1, task_id=upsertDbTest, run_id=manual__2024-06-09T10:50:44.895269+00:00, execution_date=20240609T105044, start_date=20240609T105054, end_date=20240609T105056
[2024-06-09T10:50:56.306+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-09T10:50:56.336+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-09T10:50:56.343+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
