[2024-06-08T03:03:17.894+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-08T03:03:18.193+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_t1.customOperator_test scheduled__2024-06-07T00:00:00+00:00 [queued]>
[2024-06-08T03:03:18.527+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_t1.customOperator_test scheduled__2024-06-07T00:00:00+00:00 [queued]>
[2024-06-08T03:03:18.530+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-08T03:03:19.237+0000] {taskinstance.py:2330} INFO - Executing <Task(MySqlOperator76): customOperator_test> on 2024-06-07 00:00:00+00:00
[2024-06-08T03:03:19.375+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'etl_t1', 'customOperator_test', 'scheduled__2024-06-07T00:00:00+00:00', '--job-id', '29', '--raw', '--subdir', 'DAGS_FOLDER/Etl_Dag.py', '--cfg-path', '/tmp/tmp27m00hf3']
[2024-06-08T03:03:19.452+0000] {standard_task_runner.py:91} INFO - Job 29: Subtask customOperator_test
[2024-06-08T03:03:19.491+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=171) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-06-08T03:03:19.501+0000] {standard_task_runner.py:63} INFO - Started process 189 to run task
[2024-06-08T03:03:22.242+0000] {task_command.py:426} INFO - Running <TaskInstance: etl_t1.customOperator_test scheduled__2024-06-07T00:00:00+00:00 [running]> on host 6c00989aad97
[2024-06-08T03:03:22.913+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_t1' AIRFLOW_CTX_TASK_ID='customOperator_test' AIRFLOW_CTX_EXECUTION_DATE='2024-06-07T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-07T00:00:00+00:00'
[2024-06-08T03:03:22.923+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-08T03:03:22.962+0000] {logging_mixin.py:188} INFO - using custom operator...
[2024-06-08T03:03:22.963+0000] {logging_mixin.py:188} INFO - <***.providers.mysql.hooks.mysql.MySqlHook object at 0x7fa82793de20>
[2024-06-08T03:03:23.006+0000] {base.py:84} INFO - Using connection ID 'mysql_conn' for task execution.
[2024-06-08T03:03:55.336+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-08T03:03:55.339+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/custom_operators/mySql_operator76.py", line 35, in execute
    conn = mysql_hook.get_conn()
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/mysql/hooks/mysql.py", line 195, in get_conn
    return MySQLdb.connect(**conn_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/MySQLdb/__init__.py", line 121, in Connect
    return Connection(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/MySQLdb/connections.py", line 195, in __init__
    super().__init__(*args, **kwargs2)
MySQLdb.OperationalError: (2005, "Unknown server host 'mySql' (-3)")
[2024-06-08T03:03:55.383+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=etl_t1, task_id=customOperator_test, run_id=scheduled__2024-06-07T00:00:00+00:00, execution_date=20240607T000000, start_date=20240608T030318, end_date=20240608T030355
[2024-06-08T03:03:55.420+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 29 for task customOperator_test ((2005, "Unknown server host 'mySql' (-3)"); 189)
[2024-06-08T03:03:55.448+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-08T03:03:55.477+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-08T03:03:55.480+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
