[2024-06-06T16:27:03.184+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-06T16:27:03.211+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_testConnection_v1.test_s3_hook manual__2024-06-06T16:26:57.433526+00:00 [queued]>
[2024-06-06T16:27:03.226+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_testConnection_v1.test_s3_hook manual__2024-06-06T16:26:57.433526+00:00 [queued]>
[2024-06-06T16:27:03.226+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-06T16:27:03.242+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): test_s3_hook> on 2024-06-06 16:26:57.433526+00:00
[2024-06-06T16:27:03.251+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dag_testConnection_v1', 'test_s3_hook', 'manual__2024-06-06T16:26:57.433526+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/TestConnectionDag.py', '--cfg-path', '/tmp/tmpmwmvydn4']
[2024-06-06T16:27:03.256+0000] {standard_task_runner.py:91} INFO - Job 6: Subtask test_s3_hook
[2024-06-06T16:27:03.257+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=482) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-06-06T16:27:03.258+0000] {standard_task_runner.py:63} INFO - Started process 484 to run task
[2024-06-06T16:27:03.311+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_testConnection_v1.test_s3_hook manual__2024-06-06T16:26:57.433526+00:00 [running]> on host 6c00989aad97
[2024-06-06T16:27:03.409+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_testConnection_v1' AIRFLOW_CTX_TASK_ID='test_s3_hook' AIRFLOW_CTX_EXECUTION_DATE='2024-06-06T16:26:57.433526+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-06T16:26:57.433526+00:00'
[2024-06-06T16:27:03.410+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-06T16:27:03.428+0000] {logging_mixin.py:188} INFO - <***.providers.amazon.aws.hooks.s3.S3Hook object at 0x7f5882641160>
[2024-06-06T16:27:03.441+0000] {base.py:84} INFO - Using connection ID 's3_conn' for task execution.
[2024-06-06T16:27:03.442+0000] {connection_wrapper.py:387} INFO - AWS Connection (conn_id='s3_conn', conn_type='aws') credentials retrieved from extra.
[2024-06-06T16:27:04.120+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-06T16:27:04.121+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/TestConnectionDag.py", line 34, in testS3Hook
    paths = s3_hook.list_keys(bucket_name=bucketName)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 89, in wrapper
    return func(*bound_args.args, **bound_args.kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 843, in list_keys
    for page in response:
  File "/home/airflow/.local/lib/python3.12/site-packages/botocore/paginate.py", line 269, in __iter__
    response = self._make_request(current_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/botocore/paginate.py", line 357, in _make_request
    return self._method(**current_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/botocore/client.py", line 553, in _api_call
    return self._make_api_call(operation_name, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/botocore/client.py", line 1009, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.NoSuchBucket: An error occurred (NoSuchBucket) when calling the ListObjectsV2 operation: The specified bucket does not exist
[2024-06-06T16:27:04.134+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=dag_testConnection_v1, task_id=test_s3_hook, run_id=manual__2024-06-06T16:26:57.433526+00:00, execution_date=20240606T162657, start_date=20240606T162703, end_date=20240606T162704
[2024-06-06T16:27:04.164+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 6 for task test_s3_hook (An error occurred (NoSuchBucket) when calling the ListObjectsV2 operation: The specified bucket does not exist; 484)
[2024-06-06T16:27:04.200+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-06T16:27:04.233+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-06T16:27:04.237+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
